CREATE DATABASE llc;

CREATE USER llc WITH PASSWORD 'llc';

ALTER USER llc WITH SUPERUSER;

GRANT ALL PRIVILEGES ON DATABASE llc TO llc;
GRANT ALL PRIVILEGES ON SCHEMA public TO llc;

SET TIME ZONE 'America/Montreal';
SET TIMEZONE TO 'America/Montreal';
ALTER DATABASE llc SET timezone TO 'America/Montreal';

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
